CREATE TABLE temp{
    Nombre_Victima VARCHAR2(50),
    Apellido_Victima VARCHAR2(50),
    Direccion_Victima VARCHAR2(100),
    Fecha_Sospecha DATE,
    Fecha_Confirmacion DATE,
    Fecha_Muerte DATE,
    Estado VARCHAR2(50);
    Nombre_Asociado VARCHAR2(50),
    Apellido_Asociado VARCHAR2(50),
    Fecha_Conocio DATE,
    Contacto VARCHAR2(50),
    Fecha_Inicio_Contacto DATE,
    Fecha_Final_Contacto DATE,
    Nombre_Hospital VARCHAR2(50),
    Direccion_Hospital VARCHAR2(100),
    Ubicacion_Victima VARCHAR2(100),
    Fecha_Llegada DATE,
    Fecha_Retiro DATE,
    Tratamiento VARCHAR2(50),
    Efectividad INT,
    Fecha_Inicio_Tratamiento DATE,
    Fecha_Final_Tratamiento DATE,
    Efectividad_Paciente INT
}